config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to "/games", notice: 'Game was saved.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to "/games", notice: 'Game was saved.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Save was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:rounds, :playerwins, :computerwins)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Player Wins: <%= @game.playerwins %>&emsp;
  Rounds: <%= @game.rounds %>&emsp;
  Computer Wins: <%= @game.computerwins %><br>

  <script>
  (function() {
    if( window.localStorage ) {
      if ( !localStorage.getItem( 'firstLoad' ) ) {
        localStorage[ 'firstLoad' ] = true;
        window.location.reload();
      } else
      localStorage.removeItem( 'firstLoad' );
    }
  })();

  var innerrounds = 0;
  var playerRounds = 0;
  var computerRounds = 0;

  function toggleButtons(mode) {
    if (mode == 0) {
      document.getElementById("choicebutton0").style.visibility="hidden";
      document.getElementById("choicebutton1").style.visibility="hidden";
      document.getElementById("choicebutton2").style.visibility="hidden";
      document.getElementById("endmenubutton0").style.visibility="hidden";
      document.getElementById("endmenubutton1").style.visibility="hidden";
    } else if (mode == 1) {
      document.getElementById("continuestart").remove();
      document.getElementById("choicebutton0").style.visibility="visible";
      document.getElementById("choicebutton1").style.visibility="visible";
      document.getElementById("choicebutton2").style.visibility="visible";
      document.getElementById("innerrounds").innerHTML = innerrounds
      document.getElementById("playerrounds").innerHTML = playerRounds
      document.getElementById("computerrounds").innerHTML = computerRounds
    }
  }

  function engine(playerChoice) {
    var playerwins = <%= @game.playerwins %>;
    var computerwins = <%= @game.computerwins %>;
    var rounds = <%= @game.rounds %>;
    var computerChoice =  Math.round((Math.random() * 3) + 0);

    if (playerChoice == 0 && computerChoice == 0) {
      message = "You chose Rock; Computer chose Rock\nTie";
    } else if (playerChoice == 0 && computerChoice == 1) {
      message = "You chose Rock; Computer chose Paper\nComputer wins 1 point";
      computerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 0 && computerChoice == 2) {
      message = "You chose Rock; Computer chose Scissors\nYou win 1 point";
      playerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 1 && computerChoice == 0) {
      message = "You chose Paper; Computer chose Rock\nYou win 1 point";
      playerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 1 && computerChoice == 1) {
      message = "You chose Paper; Computer chose Paper\nTie";
    } else if (playerChoice == 1 && computerChoice == 2) {
      message = "You chose Paper; Computer chose Scissors\nComputer wins 1 point";
      computerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 2 && computerChoice == 0) {
      message = "You chose Scissors; Computer chose Rock\nComputer wins 1 point";
      computerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 2 && computerChoice == 1) {
      message = "You chose Scissors; Computer chose Paper\nYou win 1 point";
      playerRounds += 1;
      innerrounds += 1;
    } else if (playerChoice == 2 && computerChoice == 2) {
      message = "You chose Scissors; Computer chose Scissors\nTie";
    } else if (playerChoice == "start") {
      message = ""
    }
    document.getElementById("outcomemessage").innerHTML = message
    document.getElementById("playerrounds").innerHTML = playerRounds
    document.getElementById("computerrounds").innerHTML = computerRounds

    if (playerRounds == 2) {
      document.getElementById("endroundmessage").innerHTML = "You win!";
      document.getElementById("choicebutton0").remove();
      document.getElementById("choicebutton1").remove();
      document.getElementById("choicebutton2").remove();
      document.getElementById("endmenubutton0").style.visibility="visible";
      document.getElementById("endmenubutton1").style.visibility="visible";
      playerwins += 1;
      rounds += 1;
    } else if (computerRounds == 2) {
      document.getElementById("endroundmessage").innerHTML = "Computer wins!";
      document.getElementById("choicebutton0").remove();
      document.getElementById("choicebutton1").remove();
      document.getElementById("choicebutton2").remove();
      document.getElementById("endmenubutton0").style.visibility="visible";
      document.getElementById("endmenubutton1").style.visibility="visible";
      computerwins += 1;
      rounds += 1;
    } else {
      document.getElementById("endroundmessage").innerHTML =  "You are challenging Computer"
      document.getElementById("endmenubutton0").style.visibility="hidden";
      document.getElementById("endmenubutton1").style.visibility="hidden";
    }
  }
  </script>
  <body onload="toggleButtons(0)"></body>

  <h2><span id="endroundmessage"></span></h2>

  <div>Player: <span id="playerrounds"></span>&emsp;Computer: <span id="computerrounds"></span></div>

  <span id="outcomemessage"></span><br>
  <span id="rounds"></span><br>

  <input id="continuestart" type="button" onclick="toggleButtons(1);engine(start)" value="Start">

  <input id="choicebutton0" type="button" onclick="engine(0)" value="Rock">
  <input id="choicebutton1" type="button" onclick="engine(1)" value="Paper">
  <input id="choicebutton2" type="button" onclick="engine(2)" value="Scissors">

  <input id="endmenubutton0" type="button" onclick="location.reload()" value="Retry">
  <input id="endmenubutton1" type="submit" value="Exit">

  <p>
    <%= form.label :rounds %>
    <%= form.text_field :rounds %>
  </p>

  <p>
    <%= form.label :playerwins %>
    <%= form.text_field :playerwins %>
  </p>

  <p>
    <%= form.label :computerwins %>
    <%= form.text_field :computerwins %>
  </p>

<% end %>

app/views/games/edit.html.erb
<h1>Continue Game</h1>

<%= render 'form', game: @game %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to RPS V1</h1>

<table>
  <thead>
    <tr>
      <th>Save |</th>
      <th>Rounds |</th>
      <th>Player Wins |</th>
      <th>Computer Wins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% number = 0 %>
    <% @games.each do |game| %>
      <tr>
        <td><%= number; number += 1 %>.</td>
        <td><%= game.rounds %></td>
        <td><%= game.playerwins %></td>
        <td><%= game.computerwins %></td>
        <td><%= link_to 'Load', edit_game_path(game) %></td>
        <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure you want to delete this save?' + "\nPlayer Wins: #{game.playerwins}\tRounds: #{game.rounds}\tComputer Wins: #{game.computerwins}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RpsGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>